chore: remove nasa_jpl biomass product
MAAP-Project/biomass-dashboard-datasets pull request #114
Opened 2023-11-08 18:28 UTC by jjfrench

2023-11-08 18:54 UTC, wildintellect requested changes

2023-11-08 18:54 UTC, wildintellect commented on datasets/CCI_BIOMASS.json
mosaic 3f4af3705f7801257a6bc856d662440a isn't working, we don't want to merge this until we resolve the correct url in main.

2023-11-09 01:00 UTC, emileten approved these changes

2023-11-09 01:03 UTC, jjfrench commented
Here is the working CCI biomass layer:
https://biomass.dit.maap-project.org/products/cci_biomass?map=-103.3245%2C51.6477%2C8.47&lState=

NASA JPL product shown as removed under:
https://biomass.dit.maap-project.org/products

2023-11-09 01:03 UTC, merged